const tours = [
    {
        id: '1',
        title: 'Starnberger See',
        category: 'lakes',
        icon: 'fa-solid fa-water',
        image: './images/tour-1.jpeg',
        country: 'Germany',
        date: 'septemper, 2021',
        location: 'https://goo.gl/maps/MXqL54V1TmHgckZaA',
        site: 'http://www.bayregio-starnberger-see.de',
        address: 'Close to the Munich city center as it is about 25 min away via <strong>S6</strong> (Starnberg).',
        description: 'Starnberger is Germany s second- largest body of fresh water.',
        thingstodo: [
            'Ship&Boat',
            'Swimming Pool',
            'Strolling',
            'bike',
            'Picnic',
            'grillzone',
            'ice-cream',
            'cafes'
        ],
        likes: '6,911',
        duration: 10,
        price: 3,
        season: 'summer',
        featured: true,
    },
    {
        id: '2',
        title: 'Regensberg',
        category: 'cities',
        icon: 'fa-solid fa-city',
        image: './images/tour-2.jpeg',
        country: 'Germany',
        date: 'october, 2021',
        location: 'https://goo.gl/maps/95rmytUxcsF3mfWLA',
        site: 'https://www.regensburg.de/en',
        address: 'Regensberg is a city in eastern Bavaria as it is about 2 hr away Munich via <strong>Train</strong> or 1.5 hr by<strong>Car</strong> (93059 Regensburg).',
        description: 'Regensberg is among the top sights and travel attractions.',
        thingstodo: [
            'Danube river',
            'Ship',
            'Dom',
            'Theater',
            'Restaurants',
            'Cafes'
        ],
        likes: '9,006',
        duration: 12,
        price: 10,
        season: 'summer',
        featured: false,
    },
    {
        id: '3',
        title: 'langwieder see',
        category: 'lakes',
        icon: 'fa-solid fa-water',
        image: './images/tour-3.jpeg',
        country: 'Germany',
        date: 'july, 2021',
        location: 'https://goo.gl/maps/xu7xHXgkjrmpXD9d7',
        site: 'https://www.muenchen.de/freizeit/orte/119333.html',
        address: 'Close to the Munich city center as it is about 30 min away via <strong>S8 </strong>Herrsching then take the <strong>Badebus</strong> (langwieder).',
        description: 'Langwiedersee is composed of three lakes west of Munich in Bavaria.',
        thingstodo: [
            'Swimming',
            'Boat',
            'Landscape',
            'Playground',
            'Grilling',
            'Strolling',
            'Picnic',
            'Snacks'
        ],
        likes: '4,311',
        duration: 10,
        price: 3,
        season: 'summer',
        featured: true,
    },
    {
        id: '4',
        title: 'Wildpark Poing',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-4.jpeg',
        country: 'Germany',
        date: 'April, 2021',
        location: 'https://goo.gl/maps/AFk9fCbLquSPqzfM8',
        site: 'http://www.wildpark-poing.de',
        address: 'In the east of Munich as it is about 40 min away via <strong>S2 </strong>(Erding).',
        description: 'Huge wildlife park with nature trails through free roaming animals, plus zoo & bird of prey shows.',
        thingstodo: [
            'Animals',
            'Waterpark',
            'Jungle',
            'Playground',
            'Picnic',
            'kids',
            'zoo',
        ],
        likes: '9,572',
        duration: 10,
        price: 12,
        season: 'summer',
        featured: true,
    },
    {
        id: '5',
        title: 'Freizeitpark Märchenwald',
        category: 'amusement Park',
        icon: 'fa-solid fa-democrat',
        image: './images/tour-5.jpeg',
        country: 'Germany',
        date: 'March, 2021',
        location: 'https://goo.gl/maps/XaVqJ6GYJ6TFx3Xt5',
        site: 'http://www.maerchenwald-isartal.de',
        address: 'In the south of Bavaria as it is about 50 min away via <strong>S7</strong> (Wolfratshausen) or 40 min by <strong>Car</strong> (82515 Wolfratshausen).',
        description: 'Nature reserve–style zoo with animals grouped in large enclosures, as per their geographic spread.',
        thingstodo: [
            'Amusement Park',
            'Roller Coaster',
            'Story Scenes',
            'Restaurant',
            'playground',
            'kids',
        ],
        likes: '25,552',
        duration: 8,
        price: 18,
        season: 'summer',
        featured: true,
    },
    {
        id: '6',
        title: 'Tierpark Hellabrunn',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-6.jpeg',
        country: 'Germany',
        date: 'April, 2021',
        location: 'https://goo.gl/maps/7hffUyjWd2iji3F68',
        site: 'http://www.hellabrunn.de',
        address: 'In the Munich city center via <strong>U3</strong> (Tierpark).',
        description: 'Forest setting for kids rides & attractions with fairytale themes, plus playgrounds toy trains.',
        thingstodo: [
            'Animals',
            'Roller Coaster',
            'Cafes',
            'Restaurant',
            'playground',
            'kids',
            'zoo',
        ],
        likes: '3,385',
        duration: 8,
        price: 14,
        season: 'summer',
        featured: true,
    },
    {
        id: '7',
        title: 'Blombergbahn Bad Tölz',
        category: 'mountains',
        icon: 'fa-solid fa-mountain',
        image: './images/tour-7.jpeg',
        country: 'Germany',
        date: 'June, 2021',
        location: 'https://goo.gl/maps/ozS3235txbXnqTidA',
        site: 'http://www.blombergbahn.com',
        address: 'In the south of Munich as it is about 45 min away by <strong>Car</strong> (83646 Wackersberg)',
        description: 'Year-round double chair lift up Blomberg Mountain to hiking trails, a toboggan run & ski slopes.',
        thingstodo: [
            'Sliding',
            'Chairlift',
            'Mountains',
            'Hiking',
            'Snacks',
            'kids',
        ],
        likes: '3,057',
        duration: 8,
        price: 7,
        season: 'summer',
        featured: true,
    },
    {
        id: '8',
        title: 'Schliersee',
        category: 'lakes',
        icon: 'fa-solid fa-water',
        image: './images/tour-8.jpeg',
        country: 'Germany',
        date: 'May, 2021',
        location: 'https://goo.gl/maps/y9514a7gquqnsc7W6',
        site: 'https://www.schliersee.de',
        address: 'In the south of Bavaria as it is about 40 min away by <strong>Car</strong> (83727 Schliersee) or 1.5 hr via <strong>Train</strong>.',
        description: 'Schliersee has a surface area of approximately 2.2 sq. mi and is known as one of the nicest lakes in Bavaria perfect for Sightseeing.',
        thingstodo: [
            'Boat',
            'Playground',
            'Snacks',
            'Strolling',
            'Chairlift',
            'Sliding',
            'Mountains',
            'Hiking',
            'Swimming',
        ],
        likes: '3,385',
        duration: 10,
        price: 10,
        season: 'summer',
        featured: true,
    },
    {
        id: '9',
        title: 'Tegernsee',
        category: 'lakes',
        icon: 'fa-solid fa-water',
        image: './images/tour-9.jpeg',
        country: 'Germany',
        date: 'February, 2021',
        location: 'https://goo.gl/maps/141JpUGq8eC4foCVA',
        site: 'https://www.tegernsee.com',
        address: 'In the south of Bavaria as it is about 40 min away by <strong>Car</strong> (83684 Tegernsee) or 1.5 hr via <strong>Train</strong>.',
        description: 'Glacial tongue-basin alpine lake covering 3.5 sq. mi., with spa towns & hiking routes nearby.',
        thingstodo: [
            'Ship/Boat',
            'Playground',
            'Snacks',
            'Strolling',
            'Chairlift',
            'Paragliding',
            'Restaurants',
            'Cafes',
            'Swimming',
        ],
        likes: '1,510',
        duration: 10,
        price: 10,
        season: 'summer',
        featured: false,
    },
    {
        id: '10',
        title: 'Bayern park',
        category: 'amusement Park',
        icon: 'fa-solid fa-democrat',
        image: './images/tour-10.jpeg',
        country: 'Germany',
        date: 'june, 2021',
        location: 'https://goo.gl/maps/hr5jSXNuFtMZSmmF8',
        site: 'http://www.bayern-park.de',
        address: 'In the east of Bavaria as it is about 1 hr away by <strong>Car</strong> (94419 Reisbach)or 2 hr via <strong>Train</strong>.',
        description: 'Rollercoaster & water slide- filled attraction with regular, family - friendly themed events.',
        thingstodo: [
            'Amusement Park',
            'ferris wheel',
            'Alpine Slide',
            'roller coasters',
            'Drop Tower',
            'Food Courts',
            'kids',
        ],
        likes: '8,708',
        duration: 12,
        price: 30,
        season: 'summer',
        featured: true,
    },
    {
        id: '11',
        title: 'WichtelWerk München',
        category: 'indoor',
        icon: 'fa-solid fa-door-closed',
        image: './images/tour-11.jpeg',
        country: 'Germany',
        date: 'December, 2021',
        location: 'https://goo.gl/maps/3NJ1QM5NwjbjCxMX9',
        site: 'http://www.wichtel-werk.de',
        address: 'Close to the Munich city center as it is about 30 min away via <strong>S8 </strong>(Neuaubing).',
        description: 'Nice entertainment for older and younger children. Good food quality (for an indoor play area), clean and well maintained.',
        thingstodo: [
            'Indoor Playground',
            'Maze',
            'Sliding',
            'Trambolin',
            'Food',
            'kids',
        ],
        likes: '1,311',
        duration: 6,
        price: 12,
        season: 'winter',
        featured: true,
    },
    {
        id: '12',
        title: 'LEGOLAND',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-12.jpeg',
        country: 'Germany',
        date: 'July, 2021',
        location: 'https://goo.gl/maps/xVvvTx7EfFKv4JxUA',
        site: 'https://www.legoland.de',
        address: 'In the west of Bavaria as it is about 1 hr away by <strong>Car</strong> (89312 Günzburg) or 2 hr via <strong>Train</strong>.',
        description: 'Family leisure park with thrill rides & an aquarium, plus German landmarks built from Lego.',
        thingstodo: [
            'Lego City',
            'Ninjago',
            'Playground',
            'Restaurants',
            'Waterpark',
            'kids',
        ],
        likes: '26,227',
        duration: 12,
        price: 40,
        season: 'summer',
        featured: true,
    },
    {
        id: '13',
        title: 'Olympiapark',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-13.jpeg',
        country: 'Germany',
        date: 'April, 2021',
        location: 'https://goo.gl/maps/bCjtavy6cYgDNiR89',
        site: 'https://www.olympiapark.de/de/olympiapark-muenchen',
        address: 'Close to the Munich city center as it is about 20 min away via <strong>U3|U8</strong> (Olympiazentrum | Petuelring).',
        description: 'Huge Olympic park complex with a stadium, guided tours, sea life center, rock museum concerts.',
        thingstodo: [
            'Tower',
            'Sea Life',
            'Stadium',
            'lakes',
            'Playground',
        ],
        likes: '43,387',
        duration: 8,
        price: 0,
        season: 'summer',
        featured: true,
    },
    {
        id: '14',
        title: 'Isar River',
        category: 'lakes',
        icon: 'fa-solid fa-water',
        image: './images/tour-14.jpeg',
        country: 'Germany',
        date: 'May, 2021',
        location: 'https://goo.gl/maps/inoGtm9tdanbrP687',
        site: 'https://www.muenchen.de/int/en/culture-leisure/sport-fitness/lakes-munich/isar.html',
        address: 'In the Munich city center via <strong>U2</strong> (Fraunhoferstraße).',
        description: 'The Isar is a river in Tyrol, Austria and Bavaria, Germany, which is not navigable for watercraft above raft size.',
        thingstodo: [
            'Swimming',
            'Strolling',
            'Picnic',
            'Playground',
            'Bridge',
        ],
        likes: '57,877',
        duration: 6,
        price: 0,
        season: 'summer',
        featured: true,
    },
    {
        id: '15',
        title: 'Schlosspark Nymphenburg',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-15.jpeg',
        country: 'Germany',
        date: 'March, 2021',
        location: 'https://goo.gl/maps/YP34oEdeSoquzk7E8',
        site: 'http://www.schloss-nymphenburg.de',
        address: 'In the Munich city center via <strong>S3</strong> (Laim).',
        description: 'Classical English-style palace park with neat flowerbeds, ornamental pool & secluded wooded area.',
        thingstodo: [
            'Palace',
            'Garden',
            'Lake',
            'Cafes',
            'Strolling',
        ],
        likes: '22,332',
        duration: 5,
        price: 0,
        season: 'summer',
        featured: true,
    },
    {
        id: '16',
        title: 'Sea Life Munich',
        category: 'museums',
        icon: 'fas fa-archway',
        image: './images/tour-16.jpeg',
        country: 'Germany',
        date: 'January, 2021',
        location: 'https://goo.gl/maps/wkCnZwVeYD1tTN3J9',
        site: 'https://www.visitsealife.com/de/muenchen',
        address: 'Close to the Munich city center as it is about 20 min away via <strong>U3|U8 </strong>(Olympiazentrum).',
        description: 'Family - friendly exhibits with a variety of sea creatures(most offer play areas & group packages).',
        thingstodo: [
            'Aquarium',
            'Marine Life',
            'Sharks',
            'Olympiapark',
            'kids',
        ],
        likes: '7,222',
        duration: 6,
        price: 15,
        season: 'summer',
        featured: true,
    },
    {
        id: '17',
        title: 'Allgäu Skyline Park',
        category: 'amusement Park',
        icon: 'fa-solid fa-democrat',
        image: './images/tour-17.jpeg',
        country: 'Germany',
        date: 'June, 2021',
        location: 'https://goo.gl/maps/sf19jtt6LDz7sQHg6',
        site: 'https://www.skylinepark.de',
        address: 'In the west of Bavaria as it is about 1 hr away by <strong>Car</strong> (86871 Rammingen) or 2 hr via <strong> Train</strong>.',
        description: 'Family - friendly exhibits with a variety of sea creatures(most offer play areas & group packages).',
        thingstodo: [
            'Amusement Park',
            'Ferris wheel',
            'Railway',
            'Restaurant',
            'kids',
        ],
        likes: '9,229',
        duration: 10,
        price: 40,
        season: 'summer',
        featured: true,
    },
    {
        id: '18',
        title: 'Jimmys Fun Park',
        category: 'indoor',
        icon: 'fa-solid fa-door-closed',
        image: './images/tour-18.jpeg',
        country: 'Germany',
        date: 'December, 2021',
        location: 'https://goo.gl/maps/TYEhBgXtQVkkVdTD9',
        site: 'https://www.jimmys-funpark.de',
        address: 'In the west of Munich as it is about 45 min away by <strong>Car</strong> (86453 Dasing) or 1.5 hr via <strong>Train</strong>',
        description: 'fun time with my kids. Is an fine place for kids, one needs to spend an entire day over there. different options.Good eateries top with cheap menu options.',
        thingstodo: [
            'Indoor Playground',
            'Airhockey',
            'Sliding',
            'Food',
            'kids',
        ],
        likes: '1,878',
        duration: 6,
        price: 8,
        season: 'summer',
        featured: true,
    },
    {
        id: '19',
        title: 'Füssen/Neuschwanstein Castle',
        category: 'cities',
        icon: 'fa-solid fa-city',
        image: './images/tour-19.jpeg',
        country: 'Germany',
        date: 'October, 2021',
        location: 'https://goo.gl/maps/YpceZbEZX8HAsqBJA',
        site: 'https://www.neuschwanstein.de',
        address: 'In the south of Bavaria as it is about 2 hr away by <strong>Car</strong> (87645 Schwangau) or 2.5 hr via <strong>Train</strong>.',
        description: 'Turreted fairytale, 19th-century, hilltop castle built for King Ludwig II, with tours of furnished rooms.',
        thingstodo: [
            'Castle',
            'Füssen',
            'Chairlift',
            'Coaster',
            'Restaurants',
        ],
        likes: '65.225',
        duration: 12,
        price: 10,
        season: 'summer',
        featured: true,
    },
    {
        id: '20',
        title: 'Märchen-Erlebnispark Marquartstein',
        category: 'farm',
        icon: 'fab fa-pagelines',
        image: './images/tour-20.jpeg',
        country: 'Germany',
        date: 'November, 2021',
        location: 'https://maps.app.goo.gl/5zPpaECJ4KQYbucA8',
        site: 'http://www.maerchenpark.de',
        address: 'In the south of Bavaria as it is about 1 hr away by <strong> Car</strong> (83250 Marquartstein) or 1.5 hr via <strong>Train</strong>.',
        description: 'Family theme park with slides & rides set in forest & mountain scenery, plus Bavarian cuisine.',
        thingstodo: [
            'Farm',
            'Animals',
            'Playground',
            'Restaurants',
            'mountain',
            'zoo',
            'kids',
        ],
        likes: '1,647',
        duration: 10,
        price: 15,
        season: 'summer',
        featured: true,
    },
    {
        id: '21',
        title: 'Alpsee Bergwelt',
        category: 'mountains',
        icon: 'fa-solid fa-mountain',
        image: './images/tour-21.jpeg',
        country: 'Germany',
        date: 'February, 2021',
        location: 'https://goo.gl/maps/T3PWoVsUq1dymoiC6',
        site: 'http://www.alpsee-bergwelt.de',
        address: 'In the south of Bavaria as it is about 2 hr away by <strong>Car</strong> (87509 Immenstadt) or 2.5 hr via <strong> Train</strong>.',
        description: 'Thrilling Alpine roller coaster twisting & zigzagging down a forested mountainside.',
        thingstodo: [
            'Coaster',
            'Chairlift',
            'Downhills',
            'Restaurants',
            'mountain',
            'kids',
        ],
        likes: '6,901',
        duration: 10,
        price: 3,
        season: 'summer',
        featured: true,
    },
    {
        id: '22',
        title: 'Marienplatz',
        category: 'cities',
        icon: 'fa-solid fa-city',
        image: './images/tour-22.jpeg',
        country: 'Germany',
        date: 'October, 2021',
        location: 'https://goo.gl/maps/2mk3XVETdFtKKRNRA',
        site: 'https://www.muenchen.de/sehenswuerdigkeiten/orte/120347.html',
        address: 'In the Munich city center via <strong>U3|S</strong> (Marienplatz).',
        description: 'City-center square & transport hub with towering St. Peters church, 2 town halls & a toy museum, christmas market.',
        thingstodo: [
            'Rathaus',
            'Shopping',
            'Cafes',
            'Strolling',
            'Historic',
            'christmas market',
        ],
        likes: '90,668',
        duration: 6,
        price: 0,
        season: 'summer',
        featured: true,
    },
    {
        id: '23',
        title: 'English Garden',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-23.jpeg',
        country: 'Germany',
        date: 'May, 2021',
        location: 'https://goo.gl/maps/ZA43nNzeaSaaS8yv6',
        site: 'https://www.muenchen.de/sehenswuerdigkeiten/orte/120242.html',
        address: 'In the Munich city center via <strong>U3|U6</strong> (Gislastraße).',
        description: 'Expansive, 18th-century, urban park with 78km of cycling/jogging trails & a lakeside beer garden.',
        thingstodo: [
            'lakes',
            'Surfing',
            'Playground',
            'Strolling',
            'Cafes',
            'picnic',
        ],
        likes: '49,422',
        duration: 8,
        price: 0,
        season: 'summer',
        featured: true,
    },
    {
        id: '24',
        title: 'Münchner Freiheit',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-24.jpeg',
        country: 'Germany',
        date: 'March, 2021',
        location: 'https://goo.gl/maps/3Dx3Yqkzyw3PJB8aA',
        site: 'http://www.muenchen.de/sehenswuerdigkeiten/orte/120324.html',
        address: 'In the Munich city center via <strong>U3|U6</strong> (Münchner Freiheit).',
        description: 'Bustling square featuring shops, pubs, restaurants & an annual Christmas market.',
        thingstodo: [
            'Shopping',
            'Playground',
            'icecream',
            'Restaurants',
            'Cafes',
            'Christmas market',
        ],
        likes: '2,006',
        duration: 6,
        price: 0,
        season: 'summer',
        featured: true,
    },
    {
        id: '25',
        title: 'Circus Krone',
        category: 'indoor',
        icon: 'fa-solid fa-door-closed',
        image: './images/tour-25.jpeg',
        country: 'Germany',
        date: 'March, 2021',
        location: 'https://goo.gl/maps/vdEzDA6HwZcVRyhp8',
        site: 'https://www.circus-krone.com/de',
        address: 'In the Munich city center via <strong>S</strong> (Hackerbrücke).',
        description: 'Circular building hosting pop & rock concerts, plus winter home of circus troupe.',
        thingstodo: [
            'Lion',
            'Clown',
            'Acrobats',
            'Snacks',
            'animals',
            'kids',
        ],
        likes: '4,426',
        duration: 3,
        price: 20,
        season: 'summer',
        featured: true,
    },
    {
        id: '26',
        title: 'Deutsches Museum',
        category: 'museums',
        icon: 'fas fa-archway',
        image: './images/tour-26.jpeg',
        country: 'Germany',
        date: 'December, 2021',
        location: 'https://goo.gl/maps/kcJd6yWHjtSN7xTRA',
        site: 'http://www.deutsches-museum.de',
        address: 'In the Munich city center via <strong>S</strong> (Isartor).',
        description: 'Huge technology museum with original artifacts & interactive energy, transport & astronomy displays.',
        thingstodo: [
            'Physics',
            'Planetarium',
            'Technology',
            'Restaurant',
            'kids',
        ],
        likes: '25,231',
        duration: 4,
        price: 7,
        season: 'summer',
        featured: true,
    },
    {
        id: '27',
        title: 'Hirschgarten',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-27.jpeg',
        country: 'Germany',
        date: 'April, 2021',
        location: 'https://goo.gl/maps/9A9aawc6fx6Z4eps5',
        site: 'https://www.muenchen.de/sehenswuerdigkeiten/orte/120223.html',
        address: 'Close to the Munich city center as it is about 15 min away via <strong>S</strong> (Laim).',
        description: 'Venerable restaurant with a charming vibe featuring traditional Bavarian fare & a huge beer garden.',
        thingstodo: [
            'Picnic',
            'Playground',
            'Deer',
            'Cafes',
            'animals',
            'kids',
        ],
        likes: '5,852',
        duration: 8,
        price: 0,
        season: 'summer',
        featured: true,
    },
    {
        id: '28',
        title: 'Riemer Park',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-28.jpeg',
        country: 'Germany',
        date: 'Aguset, 2021',
        location: 'https://goo.gl/maps/K6hurs8Zx4rVJXJ59',
        site: 'https://www.muenchen.de/sehenswuerdigkeiten/orte/119360.html',
        address: 'In the east of Munich about 15 min away via <strong>U2</strong> (Messestadt West).',
        description: ' It makes up a fresh water area of approximately 7.7 hectares, and is 14 meters deep, in some areas as deep as 18 meters. The lake is surrounded by the park which includes a north shore, pier and beach area that makes up another 6.1 hectares.',
        thingstodo: [
            'Swimming',
            'Playground',
            'Strolling',
            'Restaurants',
            'Riem Arcaden',
        ],
        likes: '649',
        duration: 8,
        price: 0,
        season: 'summer',
        featured: true,
    },
    {
        id: '29',
        title: 'Beerencafe',
        category: 'farm',
        icon: 'fab fa-pagelines',
        image: './images/tour-29.jpeg',
        country: 'Germany',
        date: 'June, 2021',
        location: 'https://goo.gl/maps/3q5DcANWs3RxkKuA6',
        site: 'https://www.hofreiter.de/beerencaf%C3%A9/',
        address: 'Close to the Munich city center as it is about 20 min away via <strong>S3</strong> (Lochhausen).',
        description: 'Fruit bowls & cakes with berries at a family-friendly site with strawberry picking & kids games.',
        thingstodo: [
            'Strawberry Picking',
            'Cafe',
            'Shakes',
            'Restaurant',
            'kids',
        ],
        likes: '1,351',
        duration: 3,
        price: 4,
        season: 'summer',
        featured: true,
    },
    {
        id: '30',
        title: 'Westpark',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-30.jpeg',
        country: 'Germany',
        date: 'June, 2021',
        location: 'https://goo.gl/maps/2GGBwpDosCRvAHbD6',
        site: 'http://www.muenchen.de/sehenswuerdigkeiten/orte/120259.html',
        address: 'Close to the Munich city center as it is about 15 min away via <strong>S7</strong> (Harras) or <strong>U6</strong>(Westpark) or U5(westendstraße).',
        description: 'Fruit bowls & cakes with berries at a family-friendly site with strawberry picking & kids games.',
        thingstodo: [
            'Picnic',
            'lakes',
            'Playground',
            'Cafes',
            'Strolling',
        ],
        likes: '8,438',
        duration: 6,
        price: 0,
        season: 'summer',
        featured: true,
    },
];