const tours = [
    {
        id: '1',
        title: 'Starnberger See',
        category: 'lakes',
        icon: 'fa-solid fa-water',
        image: './images/tour-1.jpeg',
        country: 'Germany',
        date: 'septemper, 2021',
        location: 'https://goo.gl/maps/MXqL54V1TmHgckZaA',
        site: 'http://www.bayregio-starnberger-see.de',
        address: 'Close to the Munich city center as it is about 25 min away via <strong>S6</strong> (Starnberg).',
        description: 'Starnberger is Germany s second- largest body of fresh water.',
        thingstodo: [
            'Ship&Boat',
            'Swimming Pool',
            'Strolling',
            'bike',
            'Picnic',
            'grillzone',
            'ice-cream',
            'cafes'
        ],
        likes: 6.900,
        duration: 10,
        price: 3,
        season: 'summer',
        featured: true,
    },
    {
        id: '2',
        title: 'Regensberg',
        category: 'cities',
        icon: 'fa-solid fa-city',
        image: './images/tour-2.jpeg',
        country: 'Germany',
        date: 'october, 2021',
        location: 'https://goo.gl/maps/95rmytUxcsF3mfWLA',
        site: 'https://www.regensburg.de/en',
        address: 'Regensberg is a city in eastern Bavaria as it is about 2 hr away Munich via <strong>Train</strong> or 1.5 hr by<strong>Car</strong> (93059 Regensburg).',
        description: 'Regensberg is among the top sights and travel attractions.',
        thingstodo: [
            'Danube river',
            'Ship',
            'Dom',
            'Theater',
            'Restaurants',
            'Cafes'
        ],
        likes: 9.006,
        duration: 12,
        price: 10,
        season: 'summer',
        featured: false,
    },
    {
        id: '3',
        title: 'langwieder see',
        category: 'lakes',
        icon: 'fa-solid fa-water',
        image: './images/tour-3.jpeg',
        country: 'Germany',
        date: 'july, 2021',
        location: 'https://goo.gl/maps/xu7xHXgkjrmpXD9d7',
        site: 'https://www.muenchen.de/freizeit/orte/119333.html',
        address: 'Close to the Munich city center as it is about 30 min away via <strong>S8 </strong>Herrsching then take the <strong>Badebus</strong> (langwieder).',
        description: 'Langwiedersee is composed of three lakes west of Munich in Bavaria.',
        thingstodo: [
            'Swimming',
            'Boat',
            'Landscape',
            'Playground',
            'Grilling',
            'Strolling',
            'Picnic',
            'Snacks'
        ],
        likes: 4.300,
        duration: 10,
        price: 3,
        season: 'summer',
        featured: true,
    },
    {
        id: '4',
        title: 'Wildpark Poing',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-4.jpeg',
        country: 'Germany',
        date: 'April, 2021',
        location: 'https://goo.gl/maps/AFk9fCbLquSPqzfM8',
        site: 'http://www.wildpark-poing.de',
        address: 'In the east of Munich as it is about 40 min away via <strong>S2 </strong>(Erding).',
        description: 'Huge wildlife park with nature trails through free roaming animals, plus zoo & bird of prey shows.',
        thingstodo: [
            'Animals',
            'Waterpark',
            'Jungle',
            'Playground',
            'Picnic',
            'kids',
            'zoo',
        ],
        likes: 9.572,
        duration: 10,
        price: 12,
        season: 'summer',
        featured: true,
    },
    {
        id: '5',
        title: 'Freizeitpark Märchenwald',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-5.jpeg',
        country: 'Germany',
        date: 'March, 2021',
        location: 'https://goo.gl/maps/XaVqJ6GYJ6TFx3Xt5',
        site: 'http://www.maerchenwald-isartal.de',
        address: 'In the south of Bavaria as it is about 50 min away via <strong>S7</strong> (Wolfratshausen) or 40 min by <strong>Car</strong> (82515 Wolfratshausen).',
        description: 'Nature reserve–style zoo with animals grouped in large enclosures, as per their geographic spread.',
        thingstodo: [
            'Amusement Park',
            'Roller Coaster',
            'Story Scenes',
            'Restaurant',
            'playground',
            'kids',
        ],
        likes: 25.552,
        duration: 8,
        price: 18,
        season: 'summer',
        featured: true,
    },
    {
        id: '6',
        title: 'Tierpark Hellabrunn',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-6.jpeg',
        country: 'Germany',
        date: 'April, 2021',
        location: 'https://goo.gl/maps/7hffUyjWd2iji3F68',
        site: 'http://www.hellabrunn.de',
        address: 'In the Munich city center via <strong>U3</strong> (Tierpark).',
        description: 'Forest setting for kids rides & attractions with fairytale themes, plus playgrounds toy trains.',
        thingstodo: [
            'Animals',
            'Roller Coaster',
            'Cafes',
            'Restaurant',
            'playground',
            'kids',
            'zoo',
        ],
        likes: 3.385,
        duration: 8,
        price: 14,
        season: 'summer',
        featured: true,
    },
    {
        id: '7',
        title: 'Blombergbahn Bad Tölz',
        category: 'mountains',
        icon: 'fa-solid fa-mountain',
        image: './images/tour-7.jpeg',
        country: 'Germany',
        date: 'June, 2021',
        location: 'https://goo.gl/maps/ozS3235txbXnqTidA',
        site: 'http://www.blombergbahn.com',
        address: 'In the south of Munich as it is about 45 min away by <strong>Car</strong> (83646 Wackersberg)',
        description: 'Year-round double chair lift up Blomberg Mountain to hiking trails, a toboggan run & ski slopes.',
        thingstodo: [
            'Sliding',
            'Chairlift',
            'Mountains',
            'Hiking',
            'Snacks',
            'kids',
        ],
        likes: 3.057,
        duration: 8,
        price: 7,
        season: 'summer',
        featured: true,
    },
    {
        id: '8',
        title: 'Schliersee',
        category: 'lakes',
        icon: 'fa-solid fa-water',
        image: './images/tour-8.jpeg',
        country: 'Germany',
        date: 'May, 2021',
        location: 'https://goo.gl/maps/y9514a7gquqnsc7W6',
        site: 'https://www.schliersee.de',
        address: 'In the south of Bavaria as it is about 40 min away by <strong>Car</strong> (83727 Schliersee) or 1.5 hr via <strong>Train</strong>.',
        description: 'Schliersee has a surface area of approximately 2.2 sq. mi and is known as one of the nicest lakes in Bavaria perfect for Sightseeing.',
        thingstodo: [
            'Boat',
            'Playground',
            'Snacks',
            'Strolling',
            'Chairlift',
            'Sliding',
            'Mountains',
            'Hiking',
            'Swimming',
        ],
        likes: 3.385,
        duration: 10,
        price: 10,
        season: 'summer',
        featured: true,
    },
    {
        id: '9',
        title: 'Tegernsee',
        category: 'lakes',
        icon: 'fa-solid fa-water',
        image: './images/tour-9.jpeg',
        country: 'Germany',
        date: 'February, 2021',
        location: 'https://goo.gl/maps/141JpUGq8eC4foCVA',
        site: 'https://www.tegernsee.com',
        address: 'In the south of Bavaria as it is about 40 min away by <strong>Car</strong> (83684 Tegernsee) or 1.5 hr via <strong>Train</strong>.',
        description: 'Glacial tongue-basin alpine lake covering 3.5 sq. mi., with spa towns & hiking routes nearby.',
        thingstodo: [
            'Ship/Boat',
            'Playground',
            'Snacks',
            'Strolling',
            'Chairlift',
            'Paragliding',
            'Restaurants',
            'Cafes',
            'Swimming',
        ],
        likes: 1.510,
        duration: 10,
        price: 10,
        season: 'summer',
        featured: false,
    },
    {
        id: '10',
        title: 'Bayern park',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-10.jpeg',
        country: 'Germany',
        date: 'june, 2021',
        location: 'https://goo.gl/maps/hr5jSXNuFtMZSmmF8',
        site: 'http://www.bayern-park.de',
        address: 'In the east of Bavaria as it is about 1 hr away by <strong>Car</strong> (94419 Reisbach)or 2 hr via <strong>Train</strong>.',
        description: 'Rollercoaster & water slide- filled attraction with regular, family - friendly themed events.',
        thingstodo: [
            'Amusement Park',
            'ferris wheel',
            'Alpine Slide',
            'roller coasters',
            'Drop Tower',
            'Food Courts',
            'kids',
        ],
        likes: 8.708,
        duration: 12,
        price: 30,
        season: 'summer',
        featured: true,
    },
    {
        id: '11',
        title: 'WichtelWerk München',
        category: 'Indoor',
        icon: 'fa-solid fa-door-closed',
        image: './images/tour-11.jpeg',
        country: 'Germany',
        date: 'December, 2021',
        location: 'https://goo.gl/maps/3NJ1QM5NwjbjCxMX9',
        site: 'http://www.wichtel-werk.de',
        address: 'Close to the Munich city center as it is about 30 min away via <strong>S8 </strong>(Neuaubing).',
        description: 'Nice entertainment for older and younger children. Good food quality (for an indoor play area), clean and well maintained.',
        thingstodo: [
            'Indoor Playground',
            'Maze',
            'Sliding',
            'Trambolin',
            'Food',
            'kids',
        ],
        likes: 1.310,
        duration: 6,
        price: 12,
        season: 'winter',
        featured: true,
    },
    {
        id: '12',
        title: 'LEGOLAND',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-12.jpeg',
        country: 'Germany',
        date: 'July, 2021',
        location: 'https://goo.gl/maps/xVvvTx7EfFKv4JxUA',
        site: 'https://www.legoland.de',
        address: 'In the west of Bavaria as it is about 1 hr away by <strong>Car</strong> (89312 Günzburg) or 2 hr via <strong>Train</strong>.',
        description: 'Family leisure park with thrill rides & an aquarium, plus German landmarks built from Lego.',
        thingstodo: [
            'Lego City',
            'Ninjago',
            'Playground',
            'Restaurants',
            'Waterpark',
            'kids',
        ],
        likes: 26.227,
        duration: 12,
        price: 40,
        season: 'summer',
        featured: true,
    },
    {
        id: '13',
        title: 'Olympiapark',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-13.jpeg',
        country: 'Germany',
        date: 'April, 2021',
        location: 'https://goo.gl/maps/bCjtavy6cYgDNiR89',
        site: 'https://www.olympiapark.de/de/olympiapark-muenchen',
        address: 'Close to the Munich city center as it is about 20 min away via <strong>U3|U8</strong> (Olympiazentrum | Petuelring).',
        description: 'Huge Olympic park complex with a stadium, guided tours, sea life center, rock museum concerts.',
        thingstodo: [
            'Tower',
            'Sea Life',
            'Stadium',
            'lakes',
            'Playground',
        ],
        likes: 43.387,
        duration: 8,
        price: 0,
        season: 'summer',
        featured: true,
    },
    {
        id: '14',
        title: 'Isar River',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-14.jpeg',
        country: 'Germany',
        date: 'May, 2021',
        location: 'https://goo.gl/maps/inoGtm9tdanbrP687',
        site: 'https://www.muenchen.de/int/en/culture-leisure/sport-fitness/lakes-munich/isar.html',
        address: 'In the Munich city center via <strong>U2</strong> (Fraunhoferstraße).',
        description: 'The Isar is a river in Tyrol, Austria and Bavaria, Germany, which is not navigable for watercraft above raft size.',
        thingstodo: [
            'Swimming',
            'Strolling',
            'Picnic',
            'Playground',
            'Bridge',
        ],
        likes: 57.877,
        duration: 6,
        price: 0,
        season: 'summer',
        featured: true,
    },
    {
        id: '15',
        title: 'Schlosspark Nymphenburg',
        category: 'parks',
        icon: 'fa-solid fa-tree',
        image: './images/tour-15.jpeg',
        country: 'Germany',
        date: 'March, 2021',
        location: 'https://goo.gl/maps/YP34oEdeSoquzk7E8',
        site: 'http://www.schloss-nymphenburg.de',
        address: 'In the Munich city center via <strong>S3</strong> (Laim).',
        description: 'Classical English-style palace park with neat flowerbeds, ornamental pool & secluded wooded area.',
        thingstodo: [
            'Palace',
            'Garden',
            'Lake',
            'Cafes',
            'Strolling',
        ],
        likes: 22.332,
        duration: 5,
        price: 0,
        season: 'summer',
        featured: true,
    },
];